### PR TITLE
Initial attempt at Java App Log formats

### PR DESCRIPTION
**Pull request by EdHurtig**
@mgreene could you please fill me in on what  the data between the square brackets is so I can rename the `thingidkabout` and `thing2idkabout` to something meaningful?

### CODE REVIEW

**Comment by EdHurtig** [comment]
Example of a log

```
07/08/2015 20:28:46,841 [qtp1412532858-107] INFO com.et.blah.blah - [Something?] - Took 82 ms to verify against API.

```

**Comment by jeffbyrnes** [comment]
@EdHurtig edited the description to actually notify Mark. Damned screennames.

**Comment by mgreene** [comment]
@EdHurtig do you need anything further from me here?

**Comment by EdHurtig** [comment]
All set thanks @mgreene

**Pull request merged**
